"""added requests

Revision ID: 79393285d6d5
Revises: aa1f94993078
Create Date: 2023-12-22 23:39:05.057181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79393285d6d5'
down_revision = 'aa1f94993078'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
