"""updated user

Revision ID: 9ad84b4aec4a
Revises: 62e19a892d27
Create Date: 2023-12-23 02:03:41.808949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad84b4aec4a'
down_revision = '62e19a892d27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
